In [1]:
import gym
import warnings
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

# Suppress DeprecationWarnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import tensorflow as tf

# List all GPUs available to TensorFlow
gpus = tf.config.list_physical_devices('GPU')

# Check if any GPUs are available
if len(gpus) > 0:
    print("GPU is available")
    for gpu in gpus:
        print(f"GPU device: {gpu}")
else:
    print("GPU is not available")

2023-10-18 17:42:39.620823: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-18 17:42:41.964994: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-18 17:42:48.732361: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


GPU is available
GPU device: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
GPU device: PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')
GPU device: PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU')
GPU device: PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')
GPU device: PhysicalDevice(name='/physical_device:GPU:4', device_type='GPU')


In [4]:
# Question 1: Cartpole-v0
env = gym.make(
    "CartPole-v0",
    # render_mode="human"
    )

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)


def CartPole_RL(model, discount_factor=0.95, num_choices=2):
    
    # Save rewards for visualization later
    episode_rewards = []

    for episode in range(1000):
        # print(f"CartPole-v0, episode {episode}")
        # Initiate one episode
        observation, info = env.reset()

        obs_history = []
        reward_history = []
        action_history = []

        terminated = False
        truncated = False



        # Roll out one episode
        while (not terminated) and (not truncated):

            # Make a prediction based on the state
            probabilities = model.predict(np.array([observation]), verbose=0)[0]
            # print(probabilities)

            # This line stochastically samples an action based on the probabilities
            action = np.random.choice(num_choices, p=probabilities)
            # print(action)

            obs_history.append(observation)
            action_history.append(action)

            observation, reward, terminated, truncated, info = env.step(action)
            print(observation, reward, terminated, truncated, info)

            reward_history.append(reward)
            


        
        # Discount rewards
        discounted_rewards = []
        cumulative_reward = 0
        for reward in reversed(reward_history):
            cumulative_reward = reward + discount_factor * cumulative_reward
            discounted_rewards.insert(0, cumulative_reward)

        # print(f"Cumulative Reward History: {discounted_rewards}")


        # print(f"Frame: {count_frame}")
        # print(f"Obs History: {obs_history}")
        # print(f"Reward History: {reward_history}")
        # print(f"Action History: {action_history}")



        def adjust_weights(obs_history, action_history, discounted_rewards):
            
            with tf.GradientTape() as tape:
                # Predict action probabilities
                action_probabilities = model(np.array(obs_history))
                # print(action_probabilities)

                # Get probabilities of actions that were taken
                indices = list(zip(range(len(action_history)), action_history))
                # print(indices)
                chosen_action_probs = tf.gather_nd(action_probabilities, indices)
                # print(chosen_action_probs)

                # Compute loss
                loss = -tf.math.log(chosen_action_probs) * discounted_rewards
                loss = tf.reduce_mean(loss)

                
            # Calculate gradients
            grads = tape.gradient(loss, model.trainable_variables)
            # print(grads)
            
            # Apply gradients to model weights
            optimizer.apply_gradients(zip(grads, model.trainable_variables))

            # # Print updated model weights
            # for var in model.trainable_variables:
            #     print(var.name, var.numpy()[1])


        adjust_weights(obs_history=obs_history, action_history=action_history, discounted_rewards=discounted_rewards)


        # Append episode rewards for plotting
        total_reward = sum(reward_history)
        episode_rewards.append(total_reward)
        print(f"CartPole-v0 episode {episode}, reward sum: {total_reward}")

        # clear_output(wait=True)
        
    env.close()

    # After the for loop
    plt.plot(episode_rewards)
    plt.xlabel("Episode")
    plt.ylabel("Total Reward")
    plt.show()

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation="relu", input_shape=(4,)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(2, activation="softmax")
])

CartPole_RL(model)

### Question 2 (Pong)

In [1]:
import gym
import os
import warnings
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import time  # Debug

# Suppress DeprecationWarnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

def check_gpu_availability():
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        print("GPU is available", flush=True)
        for gpu in gpus:
            print(f"GPU device: {gpu}", flush=True)
            tf.config.experimental.set_memory_growth(gpu, True)

        os.environ["CUDA_VISIBLE_DEVICES"] = "0" # Set the second GPU as available
        os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2" # Filter out warnings

    else:
        print("GPU is not available", flush=True)

check_gpu_availability()

GPU is available
GPU device: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [2]:
import gym
import os
import warnings
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

import time  # Debug

# Suppress DeprecationWarnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

def check_gpu_availability():
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        print("GPU is available", flush=True)
        for gpu in gpus:
            print(f"GPU device: {gpu}", flush=True)
            tf.config.experimental.set_memory_growth(gpu, True)

        os.environ["CUDA_VISIBLE_DEVICES"] = "0" # Set the second GPU as available
        os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2" # Filter out warnings

    else:
        print("GPU is not available", flush=True)

check_gpu_availability()

def preprocess(image, downsample_factor=2):
    """ prepro 210x160x3 uint8 frame into 6400 (80x80) 2D float array """
    image = image[35:195] # crop
    image = image[::downsample_factor,::downsample_factor,0] # downsample by factor of 2
    image[image == 144] = 0 # erase background (background type 1)
    image[image == 109] = 0 # erase background (background type 2)
    image[image != 0] = 1 # everything else (paddles, ball) just set to 1
    # In preprocess function
    return tf.reshape(tf.cast(image, tf.float32), [80, 80, 1])


def build_model(input_shape=(80, 80, 1), num_choices=2, reg=0.0001):
    model = tf.keras.Sequential([
        tf.keras.layers.Flatten(input_shape=input_shape),  # Set input_shape here
        tf.keras.layers.Dense(256, activation='relu'),  # Dense hidden layer
        tf.keras.layers.Dense(num_choices, activation="softmax")  # Dense output layer
    ])
    return model 


def select_action(model, observation):
    probabilities = model.predict(tf.expand_dims(observation, axis=0), verbose=0)[0]
    action_idx = np.random.choice([0, 1], p=probabilities)  # Choose between indices 0 and 1
    return action_idx  # Return the selected action index (either 0 or 1)


def compute_discounted_rewards(reward_history, discount_factor=0.99):
    discounted_rewards, cumulative_reward = [], 0
    for reward in reversed(reward_history):
        cumulative_reward = reward + discount_factor * cumulative_reward
        discounted_rewards.insert(0, cumulative_reward)
    
    # Normalization of discounted rewards
    mean = np.mean(discounted_rewards)
    std = np.std(discounted_rewards)
    normalized_rewards = (discounted_rewards - mean) / (std + 1e-8)  # Added epsilon to avoid division by zero
    
    return normalized_rewards

def adjust_weights(model, optimizer, obs_history, action_history, discounted_rewards):
    # Added print statement to observe the incoming discounted_rewards
    # print(f"Initial discounted_rewards: {discounted_rewards}")

    # print("Getting discounted rewards", flush=True)
    discounted_rewards = tf.convert_to_tensor(discounted_rewards, dtype=tf.float32)

    # Added print statement to observe the tensor-converted discounted_rewards
    # print(f"Tensor-converted discounted_rewards: {discounted_rewards}")

    with tf.GradientTape() as tape:
        # print("Getting probs", flush=True)
        probs = model(tf.convert_to_tensor(obs_history, dtype=tf.float32))

        # Added print statement to observe the model probabilities
        # print(f"Model probabilities: {probs}")

        # print("Getting Indices", flush=True)
        indices = tf.stack([tf.range(len(action_history), dtype=tf.int32), tf.convert_to_tensor(action_history, dtype=tf.int32)], axis=1)

        # Added print statement to observe the indices
        # print(f"indices: {indices}")

        # print("Getting Chosen Probs", flush=True)
        chosen_probs = tf.gather_nd(probs, indices)

        # Added print statement to observe the chosen probabilities
        # print(f"Chosen probabilities: {chosen_probs}")
        # print(f"Chosen probabilities: {chosen_probs[:4].numpy()}")

        # print("Getting Loss", flush=True)
        loss = -tf.math.log(chosen_probs) * discounted_rewards
        loss = tf.reduce_sum(loss)

        # Added print statement to observe the loss
        print(f"Loss: {loss}")

    # print("Applying Gradient and Optimizer", flush=True)
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    # Added print statement to observe the applied gradients
    # print(f"Applied gradients: {grads}")



def save_plot(episode_rewards, episode):
    window = 100  # Size of the window for calculating moving average
    moving_avgs = [np.mean(episode_rewards[max(0, i - window + 1):i + 1]) for i in range(len(episode_rewards))]
    
    plt.plot(episode_rewards, label='Total Reward')
    plt.plot(moving_avgs, label=f'{window}-Episode Moving Average')
    plt.xlabel("Episode")
    plt.ylabel("Total Reward")
    plt.legend()
    plt.savefig(f'artifacts/pong_rewards_{episode}.png')
    plt.close()

def Pong_RL():
    env = gym.make("Pong-v0")
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
    model = build_model()
    episode_rewards = []
    episode = 0 

    consecutive_21_rewards = 0  # Count number of 21 occurences
    should_train = True  # Initialize flag for training

    while True:
        observation, info = env.reset()
        obs_history, reward_history, action_history = [], [], []

        terminated = False
        truncated = False

        # print("Starting Game", flush=True)

        while not terminated and not truncated:
            processed_observation = preprocess(observation)
            action = select_action(model, processed_observation)
            obs_history.append(processed_observation)
            action_history.append(action)

            action_to_take = 2 if action == 0 else 3  # Remap the action index to the appropriate Pong-v0 action
            observation, reward, terminated, truncated, info = env.step(action_to_take)
            
            reward_history.append(reward)

        # print("Finishing Game", flush=True)

        discounted_rewards = compute_discounted_rewards(reward_history)

        total_reward = sum(reward_history)
        episode_rewards.append(total_reward)

        moving_num, window = 0, 100
        if episode >= window-1:
            moving_avg = np.mean(episode_rewards[-window:])
            print(f"Pong-v0 episode {episode}, reward sum: {total_reward}, last {window} avg: {moving_avg:.2f}", flush=True)
            
            if moving_avg > moving_num:
                print(f"Stopping as the last {window}-episode moving average is greater than {moving_num}", flush=True)
                break
        else:
            print(f"Pong-v0 episode {episode}, reward sum: {total_reward}", flush=True)

        ### TRAINING STOP

        if total_reward == 21:  # Check for consecutive rewards of 21
            consecutive_21_rewards += 1
            if consecutive_21_rewards >= 10 and should_train == True:
                print("Stopping training as the reward has been 21 for 10 episodes in a row", flush=True)
                should_train = False  # Set flag to False

                # Check if folder exists, if not create it
                if not os.path.exists("saved_model"):
                    os.makedirs("saved_model")

                # Save the model
                model.save("saved_model/pong_model")
                
        else:
            consecutive_21_rewards = 0  # Reset the counter if the reward is not 21

        # Modify the weight adjustment to respect the should_train flag
        # print("Starting Model Training", flush=True)
        if should_train:
            adjust_weights(model, optimizer, obs_history, action_history, discounted_rewards)
        # print("Ending Model Training", flush=True)

        # Save the model every 100 iterations
        if episode % 100 == 0:
            model.save(f"saved_model/pong_model_{episode}")
            
        # Save a reward plot every iteration
        save_plot(episode_rewards, episode)

        episode += 1

    env.close()

    # Save Results
    if not os.path.exists('artifacts'):
        os.makedirs('artifacts')

    # Calculate moving average of rewards
    window = 100  # Size of the window for calculating moving average
    moving_avgs = [np.mean(episode_rewards[max(0, i - window + 1):i+1]) for i in range(len(episode_rewards))]

    plt.plot(episode_rewards, label='Total Reward')
    plt.plot(moving_avgs, label=f'{window}-Episode Moving Average')
    plt.xlabel("Episode")
    plt.ylabel("Total Reward")
    plt.legend()
    plt.savefig('artifacts/pong_rewards.png')

Pong_RL()

GPU is available
GPU device: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


c:\Users\nuke2\Desktop\NW Work\Fall_02 Work\MSIA-FQ2\.venv\lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment Pong-v0 is out of date. You should consider upgrading to version `v4`.
  logger.warn(


Pong-v0 episode 0, reward sum: -21.0
Initial discounted_rewards: [0.85944316 0.83565721 0.811631   ... 0.95875218 0.93596936 0.9129564 ]
Getting discounted rewards
Tensor-converted discounted_rewards: [0.8594432  0.83565724 0.811631   ... 0.95875216 0.93596935 0.9129564 ]
Getting probs
Model probabilities: [[0.461398   0.538602  ]
 [0.45961806 0.5403819 ]
 [0.44824216 0.5517579 ]
 ...
 [0.44648853 0.55351144]
 [0.48774722 0.51225275]
 [0.45441616 0.54558384]]
Getting Indices
indices: [[   0    1]
 [   1    1]
 [   2    0]
 ...
 [1428    0]
 [1429    0]
 [1430    1]]
Getting Chosen Probs
Chosen probabilities: [0.538602   0.5403819  0.44824216 ... 0.44648853 0.48774722 0.54558384]
Chosen probabilities: [0.538602   0.5403819  0.44824216 0.50548124]
Getting Loss
Loss: 1.8795051574707031
Applying Gradient and Optimizer
Applied gradients: [<tf.Tensor: shape=(6400, 256), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
 

INFO:tensorflow:Assets written to: saved_model/pong_model_0\assets


INFO:tensorflow:Assets written to: saved_model/pong_model_0\assets


Pong-v0 episode 1, reward sum: -21.0
Initial discounted_rewards: [1.09041128 1.07128992 1.05197541 ... 1.14291881 1.12432783 1.10554906]
Getting discounted rewards
Tensor-converted discounted_rewards: [1.0904113 1.0712899 1.0519754 ... 1.1429188 1.1243278 1.1055491]
Getting probs
Model probabilities: [[0.43674886 0.5632512 ]
 [0.5311288  0.46887118]
 [0.54907316 0.4509268 ]
 ...
 [0.51311696 0.48688307]
 [0.5244296  0.47557038]
 [0.5206432  0.47935683]]
Getting Indices
indices: [[   0    0]
 [   1    1]
 [   2    0]
 ...
 [1256    1]
 [1257    1]
 [1258    0]]
Getting Chosen Probs
Chosen probabilities: [0.43674886 0.46887118 0.54907316 ... 0.48688307 0.47557038 0.5206432 ]
Chosen probabilities: [0.43674886 0.46887118 0.54907316 0.54907316]
Getting Loss
Loss: 6.176482677459717
Applying Gradient and Optimizer
Applied gradients: [<tf.Tensor: shape=(6400, 256), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [